# Generated by Django 4.2.24 on 2025-09-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_degree',
            field=models.CharField(blank=True, help_text='PhD, Prof., Dr. və s.', max_length=100, null=True, verbose_name='Akademik dərəcə'),
        ),
        migrations.AddField(
            model_name='user',
            name='google_scholar_url',
            field=models.URLField(blank=True, null=True, verbose_name='Google Scholar profili'),
        ),
        migrations.AddField(
            model_name='user',
            name='h_index',
            field=models.PositiveIntegerField(default=0, help_text='Google Scholar və ya Scopus H-index', verbose_name='H-index'),
        ),
        migrations.AddField(
            model_name='user',
            name='orcid_id',
            field=models.CharField(blank=True, help_text='Məsələn: 0000-0000-0000-0000', max_length=30, null=True, verbose_name='ORCID ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='research_interests',
            field=models.TextField(blank=True, help_text='Vergüllərlə ayırın', null=True, verbose_name='Tədqiqat sahələri'),
        ),
        migrations.AddField(
            model_name='user',
            name='scopus_author_id',
            field=models.CharField(blank=True, help_text='Məsələn: 123456789', max_length=20, null=True, verbose_name='Scopus Author ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='scopus_h_index',
            field=models.PositiveIntegerField(default=0, verbose_name='Scopus H-index'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_citations',
            field=models.PositiveIntegerField(default=0, verbose_name='Ümumi istinadlar sayı'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_publications',
            field=models.PositiveIntegerField(default=0, verbose_name='Nəşr sayı'),
        ),
        migrations.AddField(
            model_name='user',
            name='university_affiliation',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Universitet əlaqəsi'),
        ),
    ]
