# Generated by Django 5.2.6 on 2025-09-13 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Təklif məbləği')),
                ('delivery_time', models.PositiveIntegerField(help_text='Neçə gün ərzində işi bitirəcəksiniz', verbose_name='Təhvil müddəti (gün)')),
                ('proposal', models.TextField(help_text='Nəyə görə bu işi sizə verməlidirlər?', verbose_name='Təklif təsviri')),
                ('status', models.CharField(choices=[('active', 'Aktiv'), ('accepted', 'Qəbul edildi'), ('rejected', 'Rədd edildi'), ('withdrawn', 'Geri çəkildi')], default='active', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_bids', to=settings.AUTH_USER_MODEL, verbose_name='Freelancer')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='projects.project', verbose_name='Layihə')),
            ],
            options={
                'verbose_name': 'Təklif',
                'verbose_name_plural': 'Təkliflər',
                'ordering': ['-created_at'],
                'unique_together': {('project', 'freelancer')},
            },
        ),
    ]
