# Generated by Django 5.2.6 on 2025-09-13 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Məbləğ')),
                ('payment_type', models.CharField(choices=[('project_payment', 'Layihə ödənişi'), ('milestone_payment', 'Mərhələ ödənişi'), ('bonus', 'Bonus'), ('refund', 'Geri qaytarma')], default='project_payment', max_length=50, verbose_name='Ödəniş növü')),
                ('status', models.CharField(choices=[('pending', 'Gözləmədə'), ('paid', 'Ödənildi'), ('failed', 'Uğursuz'), ('refunded', 'Geri qaytarıldı')], default='pending', max_length=20, verbose_name='Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıqlama')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tranzaksiya ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ödəniş tarixi')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_made', to=settings.AUTH_USER_MODEL, verbose_name='Ödəyici (müştəri)')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='projects.project', verbose_name='Layihə')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_received', to=settings.AUTH_USER_MODEL, verbose_name='Alan (freelancer)')),
            ],
            options={
                'verbose_name': 'Ödəniş',
                'verbose_name_plural': 'Ödənişlər',
                'ordering': ['-created_at'],
            },
        ),
    ]
