# Generated by Django 5.2.6 on 2025-09-13 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlıq')),
                ('description', models.TextField(verbose_name='Təsvir')),
                ('category', models.CharField(choices=[('article_editing', 'Məqalə Redaktəsi'), ('scopus_support', 'Scopus Dəstəyi'), ('translation', 'Tərcümə'), ('research', 'Tədqiqat'), ('proofreading', 'Korrektor'), ('formatting', 'Formatlaşdırma'), ('other', 'Digər')], max_length=50, verbose_name='Kateqoriya')),
                ('budget_min', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Minimum büdcə')),
                ('budget_max', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Maksimum büdcə')),
                ('deadline', models.DateTimeField(verbose_name='Son tarix')),
                ('status', models.CharField(choices=[('open', 'Açıq'), ('in_progress', 'İcrada'), ('completed', 'Tamamlandı'), ('cancelled', 'Ləğv edildi')], default='open', max_length=20, verbose_name='Status')),
                ('article_file', models.FileField(blank=True, help_text='PDF, DOC, DOCX formatlarında', null=True, upload_to='articles/%Y/%m/', verbose_name='Məqalə faylı')),
                ('requirements', models.TextField(blank=True, null=True, verbose_name='Əlavə tələblər')),
                ('skills_required', models.CharField(blank=True, help_text='Vergül ilə ayrılmış', max_length=500, null=True, verbose_name='Tələb olunan bacarıqlar')),
                ('urgency_level', models.CharField(choices=[('low', 'Aşağı'), ('medium', 'Orta'), ('high', 'Yüksək'), ('urgent', 'Təcili')], default='medium', max_length=20, verbose_name='Təcillik səviyyəsi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yenilənmə tarixi')),
                ('assigned_freelancer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='Təyin edilmiş freelancer')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_projects', to=settings.AUTH_USER_MODEL, verbose_name='Müştəri')),
            ],
            options={
                'verbose_name': 'Layihə',
                'verbose_name_plural': 'Layihələr',
                'ordering': ['-created_at'],
            },
        ),
    ]
